export const allCities = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Indianapolis",
    "Columbus",
    "Fort Worth",
    "Charlotte",
    "Seattle",
    "Denver",
    "El Paso",
    "Washington",
    "Boston",
    "Detroit",
    "Nashville",
    "Memphis",
    "Portland",
    "Oklahoma City",
    "Las Vegas",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Long Beach",
    "Mesa",
    "Atlanta",
    "Colorado Springs",
    "Virginia Beach",
    "Raleigh",
    "Omaha",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Wichita",
    "New Orleans",
    "Arlington",
    "Cleveland",
    "Bakersfield",
    "Tampa",
    "Aurora",
    "Honolulu",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Corpus Christi",
    "Lexington",
    "Stockton",
    "Pittsburgh",
    "Anchorage",
    "Cincinnati",
    "Saint Paul",
    "Greensboro",
    "Toledo",
    "Newark",
    "Plano",
    "Henderson",
    "Lincoln",
    "Orlando",
    "Jersey City",
    "Chula Vista",
    "Buffalo",
    "Fort Wayne",
    "Chandler",
    "St. Petersburg",
    "Laredo",
    "Durham",
    "Irvine",
    "Madison",
    "Norfolk",
    "Lubbock",
    "Gilbert",
    "Winston-Salem",
    "Glendale",
    "Reno",
    "Hialeah",
    "Garland",
    "Scottsdale",
    "Irving",
    "Chesapeake",
    "North Las Vegas",
    "Fremont",
    "Baton Rouge",
    "Richmond",
    "Boise",
    "San Bernardino",
    "Spokane",
    "Des Moines",
    "Modesto",
    "Oxnard",
    "Fontana",
    "Moreno Valley",
    "Huntington Beach",
    "Yonkers",
    "Glendale",
    "Aurora",
    "Montgomery",
    "Columbus",
    "Amarillo",
    "Little Rock",
    "Akron",
    "Shreveport",
    "Augusta",
    "Grand Rapids",
    "Mobile",
    "Salt Lake City",
    "Huntsville",
    "Tallahassee",
    "Grand Prairie",
    "Overland Park",
    "Knoxville",
    "Worcester",
    "Brownsville",
    "Newport News",
    "Santa Clarita",
    "Port St. Lucie",
    "Providence",
    "Fort Lauderdale",
    "Chattanooga",
    "Tempe",
    "Oceanside",
    "Garden Grove",
    "Rancho Cucamonga",
    "Cape Coral",
    "Santa Rosa",
    "Vancouver",
    "Sioux Falls",
    "Peoria",
    "Ontario",
    "Jackson",
    "Elk Grove",
    "Springfield",
    "Pembroke Pines",
    "Salem",
    "Eugene",
    "Corona",
    "McKinney",
    "Fort Collins",
    "Lancaster",
    "Cary",
    "Palmdale",
    "Hayward",
    "Salinas",
    "Frisco",
    "Springfield",
    "Pasadena",
    "Macon",
    "Alexandria",
    "Pomona",
    "Lakewood",
    "Sunnyvale",
    "Escondido",
    "Kansas City",
    "Hollywood",
    "Clarksville",
    "Torrance",
    "Rockford",
    "Joliet",
    "Paterson",
    "Bridgeport",
    "Naperville",
    "Savannah",
    "Mesquite",
    "Syracuse",
    "Pasadena",
    "Orange",
    "Fullerton",
    "Killeen",
    "Dayton",
    "McAllen",
    "Bellevue",
    "Miramar",
    "Hampton",
    "West Valley City",
    "Warren",
    "Olathe",
    "Columbia",
    "Thornton",
    "Carrollton",
    "Midland",
    "Charleston",
    "Waco",
    "Sterling Heights",
    "Denton",
    "Cedar Rapids",
    "New Haven",
    "Roseville",
    "Gainesville",
    "Visalia",
    "Coral Springs",
    "Thousand Oaks",
    "Elizabeth",
    "Stamford",
    "Concord",
    "Surprise",
    "Lafayette",
    "Topeka",
    "Kent",
    "Simi Valley",
    "Santa Clara",
    "Murfreesboro",
    "Hartford",
    "Athens",
    "Victorville",
    "Abilene",
    "Norman",
    "Vallejo",
    "Berkeley",
    "Round Rock",
    "Ann Arbor",
    "Fargo",
    "Columbia",
    "Allentown",
    "Evansville",
    "Beaumont",
    "Odessa",
    "Wilmington",
    "Arvada",
    "Independence",
    "Provo",
    "Lansing",
    "El Monte",
    "Springfield",
    "Fairfield",
    "Clearwater",
    "Peoria",
    "Rochester",
    "Carlsbad",
    "Westminster",
    "West Jordan",
    "Pearland",
    "Richardson",
    "Downey",
    "Miami Gardens",
    "Temecula",
    "Costa Mesa",
    "College Station",
    "Elgin",
    "Murrieta",
    "Gresham",
    "High Point",
    "Antioch",
    "Inglewood",
    "Cambridge",
    "Lowell",
    "Manchester",
    "Billings",
    "Pueblo",
    "Palm Bay",
    "Centennial",
    "Richmond",
    "Ventura",
    "Pompano Beach",
    "North Charleston",
    "Everett",
    "Waterbury",
    "West Palm Beach",
    "Boulder",
    "West Covina",
    "Broken Arrow",
    "Clovis",
    "Daly City",
    "Lakeland",
    "Santa Maria",
    "Norwalk",
    "Sandy Springs",
    "Hillsboro",
    "Green Bay"
];

export const isCityValid = (input: string) => allCities.find(city => city.toLowerCase() === input.toLowerCase())